# Generated by Django 3.1.5 on 2021-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.CharField(max_length=15)),
                ('account_status', models.CharField(default='ACTIVE', max_length=15)),
                ('currency_code', models.CharField(default='BDT', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('nid', models.CharField(blank=True, max_length=100, null=True)),
                ('tin', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(max_length=200)),
                ('request_endpoint', models.CharField(blank=True, max_length=1000, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('stacktrace', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
