# Generated by Django 3.1.5 on 2021-01-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_params',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
