# Generated by Django 3.1.5 on 2021-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0002_auto_20210127_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='idtp_vid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
