# Generated by Django 3.1.5 on 2021-02-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0005_auto_20210131_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='idtp_status',
            field=models.CharField(default='CONFIRMED', max_length=15),
        ),
    ]
