# Generated by Django 3.1.5 on 2021-02-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0006_auto_20210207_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='idtp_vid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
